### ISSUE TITLE
Sails.io not accessible on smallscreens

### ISSUE THREAD

**Issue by juaniyyoo** [balderdashy/www.sailsjs.org#52]
The website documentation section is unreadable on small resolution even if we remove the HEADER mobilespecs.

Do you think you'll make it accessible soon ?
It's frustrating not to be able to look or show some configuration stuff on small devices.

**Comment by mikermcneil** [comment]
@juaniyyoo completely agree- i've been getting around this by turning my phone sideways.  Not really a long-term solution :)  Would you be able to help make the styles responsive?  The only tricky part afaik is that it sort of needs a slide-out menu with the nested nav.

**Comment by rachaelshaw** [comment]
Closing this, since we have the landscape-orientation workaround for small screens, and no one else has mentioned this to us since Dec 2014. I can play around with some mobile navigation ideas as I have time.

**Comment by rachaelshaw** [comment]
@juaniyyoo just updated sailsjs.org so that if you're on a specific doc page on your phone, it will at least link you to the right GitHub file so you don't have to dig around for it. (See the comments in https://github.com/balderdashy/www.sailsjs.org/issues/70) Might take a bit of time for it to be on the live version of the website though since cloudflare caches it.
