### ISSUE TITLE
[Feature Request] Documentation UX Suggestions

### ISSUE THREAD

**Issue by rachaelshaw** [balderdashy/www.sailsjs.org#70]
Originally in [sails-docs](https://github.com/balderdashy/sails-docs/issues/341), via @epadillas:

>I have some suggestions/comments regarding to the doc pages :beers: 

> + Whenever I click on a topic from the concept list on the left, some javascript automatically scrolls my browser to the top of the page. It feels "unnatural" because I didn't scroll up by myself, and I could be reading the concept sub-list that is displayed after the initial click, but I'm taken away from there. With that auto-scroller, I have to scroll down again, find where I left reading, and start again.

> + It could be more practical to use less pages for each section/concept. For example, in the "Models and ORM" section, there's more than 10 sub-pages ("Associations", "Dominance", "Attributes" ...). I use ctrl+f a lot to find stuff in doc pages. I could be looking for a specific string (for example, "afterCreate"), whose terminology in the Sails framework is unknown to me. With the current division of the doc pages, it will take a little bit more time to find what I'm looking for (visiting every sub-page and ctrl-f'ing). A good example of long-page documentation is Bootstrap (http://getbootstrap.com/components/). There, if I forgot how to create badges, I'd simply ctrl+f it and it would take less than 3 seconds to find what I was looking for.

**Comment by AzriAhmad** [comment]
I have a suggestion for UX for the mobile. All documentation on the mobile site forces users to redirect to https://github.com/balderdashy/sails-docs via the 'View on Github' button. This is quite frustrating because it should redirect to the exact Github URL of which the user queried for in Google.

For example a Google search for "sailsjs .find" lands me to the mobile site:
http://sailsjs.org/documentation/reference/waterline-orm/models/find 
but the 'View on Github button' will point to https://github.com/balderdashy/sails-docs instead of https://github.com/balderdashy/sails-docs/blob/master/reference/waterline/models/find.md

I'm on Android 6.01 using the native Google Chrome browser.

**Comment by rachaelshaw** [comment]
@AzriAhmad thanks for the suggestion. It would actually be pretty simple to link to the proper documentation file on GitHub, because we already link to the GH files in the footer of each page to make it easier for people to submit PRs. I'll look into it when I have a moment.
(In the mean time, if you're looking at the docs on your phone, rotating it and looking at the page in landscape mode should show you the actual docs and not the GitHub link.)
